Bump develop
OpenSourcePolitics/decidim-cco pull request #16
Opened 2023-03-06 17:35 UTC by paulinebessoles

* Bump/0.26 stable (#11)

* Removes useless overload

* Remove meetings overload

* Avoid deploy error

---------

Co-authored-by: Armand Fardeau <armandfardeau@users.noreply.github.com>
Co-authored-by: armandfardeau <fardeauarmand@gmail.com>

2023-03-08 11:36 UTC, eliegaboriau approved these changes
LGTM except for the french locale

2023-03-08 11:36 UTC, eliegaboriau commented on config/locales/fr.yml
> +        user_menu: User menu
This should be translated

2023-03-08 15:18 UTC, armandfardeau requested changes

2023-03-08 15:18 UTC, armandfardeau commented on config/locales/fr.yml
> +        user_menu: User menu
```suggestion
        user_menu: Menu utilisateur
```

2023-03-09 09:19 UTC, armandfardeau approved these changes

2023-03-09 10:02 UTC, merged